# Generated by Django 3.2.16 on 2023-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211107_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.PositiveIntegerField(choices=[(1, 'User'), (2, 'staff'), (3, 'Admin')], default=1),
        ),
    ]
